

from typing import TypedDict, List, Optional

class Issue(TypedDict):

    """
         State of the issue hihglithing what kind issues are there :
         Attributes :
         line_number : issue on this line
         severity : if the bug is critical which might crash the logic, or just a warning or infor
         agent : which specific agent to use after the current state
         message : any additional message 
         suggestion : any extra suggestion that you want to add 
    """
    line_number: int
    severity: str        # "critical" / "warning" / "info"
    agent: str           # "syntax" / "logic" / "security"
    message: str
    suggestion: str

class AgentState(TypedDict):

    """
    This is the agent state which contains information about what
    state of the agnet should persist  like any particular 
    and additional attribitues such as the language use by the code, 
    the chunking of lines, then analyzing of the lines and create a state of the issues
    then loop control of the model and then the final report 
    """

    # --- INPUT ---
    raw_code: str                        # original code submitted
    file_name: str                       # e.g. "app.py"
    language: str                        # e.g. "python"

    # --- PARSED ---
    code_chunks: List[dict]              # [{ "lines": "1-10", "code": "..." }]
    flagged_lines: List[int]             # lines to re-analyze in loop

    # --- AGENT RESULTS ---
    syntax_issues: List[Issue]
    logic_issues: List[Issue]
    security_issues: List[Issue]

    # --- LOOP CONTROL ---
    loop_count: int                      # current iteration
    max_loops: int      = 3                 # hardcoded as 3

    # --- OUTPUT ---
    final_report: Optional[str]          # generated by report_node
    status: str                          # "in_progress" / "done" / "failed"
